//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GettingStartedClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="ServiceReference1.IFridge")]
    public interface IFridge {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/GetFruitTotal", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/GetFruitTotalResponse")]
        int GetFruitTotal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/GetFruitTotal", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/GetFruitTotalResponse")]
        System.Threading.Tasks.Task<int> GetFruitTotalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/AddFruit", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/AddFruitResponse")]
        int AddFruit(string fruit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/AddFruit", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/AddFruitResponse")]
        System.Threading.Tasks.Task<int> AddFruitAsync(string fruit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/TakeFruit", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/TakeFruitResponse")]
        int TakeFruit(string fruit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/TakeFruit", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/TakeFruitResponse")]
        System.Threading.Tasks.Task<int> TakeFruitAsync(string fruit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/FridgeContents", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/FridgeContentsResponse")]
        string[] FridgeContents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/FridgeContents", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/FridgeContentsResponse")]
        System.Threading.Tasks.Task<string[]> FridgeContentsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFridgeChannel : GettingStartedClient.ServiceReference1.IFridge, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FridgeClient : System.ServiceModel.ClientBase<GettingStartedClient.ServiceReference1.IFridge>, GettingStartedClient.ServiceReference1.IFridge {
        
        public FridgeClient() {
        }
        
        public FridgeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FridgeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FridgeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FridgeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetFruitTotal() {
            return base.Channel.GetFruitTotal();
        }
        
        public System.Threading.Tasks.Task<int> GetFruitTotalAsync() {
            return base.Channel.GetFruitTotalAsync();
        }
        
        public int AddFruit(string fruit) {
            return base.Channel.AddFruit(fruit);
        }
        
        public System.Threading.Tasks.Task<int> AddFruitAsync(string fruit) {
            return base.Channel.AddFruitAsync(fruit);
        }
        
        public int TakeFruit(string fruit) {
            return base.Channel.TakeFruit(fruit);
        }
        
        public System.Threading.Tasks.Task<int> TakeFruitAsync(string fruit) {
            return base.Channel.TakeFruitAsync(fruit);
        }
        
        public string[] FridgeContents() {
            return base.Channel.FridgeContents();
        }
        
        public System.Threading.Tasks.Task<string[]> FridgeContentsAsync() {
            return base.Channel.FridgeContentsAsync();
        }
    }
}
